apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo-server
  labels:
    app: demo-server
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
    nodePort: 30069
  selector:
    app: demo-server
    tier: backend
---
apiVersion: v1
kind: Route
metadata:
  name: demo-server
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: demo-server