
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-microservices-k8s
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo-microservices-k8s
  labels:
    app: demo-microservices-k8s
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
    nodePort: 30018
  selector:
    app: demo-microservices-k8s
    tier: backend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: demo-microservices-k8s
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: demo-microservices-k8s
        tier: backend
    spec:
      containers:
      - name: demo-microservices-k8s
        image: jjenksy/demo-microservices-k8s
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: springboot-app
          containerPort: 8080
        livenessProbe:
                  httpGet:
                    path: /actuator/health
                    port: springboot-app
                  initialDelaySeconds: 180
                  periodSeconds: 10
        readinessProbe:
                  httpGet:
                    path: /actuator/health
                    port: springboot-app
                  initialDelaySeconds: 15
                  periodSeconds: 3
#        todo have devops inject this during build process
        env:
        - name: APP_VERSION
          value: dev
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_NAME
          value: demo-microservices-k8s
        - name: LOGLEVEL
          value: DEBUG