#apiVersion: v1
#kind: Service
#metadata:
#  namespace: default
#  name: demo-microservices-k8s
#  labels:
#    app: demo-microservices-k8s
#    tier: backend
#spec:
#  type: NodePort
#  ports:
#    # the port that this service should serve on
#  - port: 8080
#    nodePort: 30018
#  selector:
#    app: demo-microservices-k8s
#    tier: backend
#
#---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: demo-microservices-k8s
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/demo-microservices-k8s
  labels:
      app: demo-microservices-k8s
      group: com.microservice.demo
      provider: jjenksy
      version: 0.0.1-SNAPSHOT
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
      matchLabels:
        app: demo-microservices-k8s
        group: com.microservice.demo
        provider: jjenksy
  template:
    metadata:
      labels:
        app: demo-microservices-k8s
        group: com.microservice.demo
        provider: jjenksy
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
      - name: demo-microservices-k8s
        image: jjenksy/demo-microservices-k8s
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: springboot-app
          containerPort: 8080
        livenessProbe:
                  httpGet:
                    path: /health
                    port: springboot-app
                  initialDelaySeconds: 180
                  periodSeconds: 10
        readinessProbe:
                  httpGet:
                    path: /health
                    port: springboot-app
                  initialDelaySeconds: 15
                  periodSeconds: 3
#        todo have devops inject this during build process
        env:
        - name: APP_VERSION
          value: dev
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: APP_NAME
          value: demo-microservices-k8s
        - name: LOGLEVEL
          value: DEBUG