kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: discovery-server
spec:
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: jjenksy/eureka-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 800Mi
          ports:
            - name: springboot-app
              containerPort: 8761
          livenessProbe:
            httpGet:
              path: /health
              port: springboot-app
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: springboot-app
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          env:
            - name: JAVA_OPTS
              value: '-Xms256m -Xmx512m -Xss1m'

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - name: discovery
      protocol: TCP
      port: 8761
      targetPort: 8761